apiVersion: v1
kind: Pod
metadata:
  name: query
  namespace: kylin-example
spec:
  containers:
  - name: kylin
    image: registry-vpc.cn-shanghai.aliyuncs.com/ecitest/kylin-client:3.1.2-hadoop2-0702a
    imagePullPolicy: Always
    env:
    - name: HADOOP_CLASSPATH
      value: $HADOOP_CLASSPATH:$HBASE_HOME/lib/*:$HBASE_HOME/lib/hbase-common-1.7.0.jar
    command:
    - sh
    - -c
    args:
    - cp $KYLIN_HOME/tomcat-config/* $KYLIN_HOME/tomcat/conf;
      cp $KYLIN_HOME/kylin-more-config $KYLIN_HOME/tomcat/webapps/kylin/WEB-INF/classes/;
      sleep 1000000;
    volumeMounts:
    - name: kylin-query-config
      mountPath: /home/apache_kylin/kylin/conf
    - name: tomcat-config
      mountPath: /home/apache_kylin/kylin/tomcat-config
    - name: kylin-more-config
      mountPath: /home/apache_kylin/kylin/kylin-more-config/
    - name: hadoop-config
      mountPath: /etc/hadoop/conf
    - name: hadoop-config
      mountPath: /apache/hadoop-2.7.4/etc/hadoop
    - name: hive-config
      mountPath: /etc/hive/conf
    - name: hive-config
      mountPath: /apache/hive/conf
    - name: hbase-config
      mountPath: /etc/hbase/conf
    - name: hbase-config
      mountPath: /apache/hbase/conf
    - name: kylin-logs
      mountPath: /home/apache_kylin/kylin/log
    - name: tomcat-logs
      mountPath: /home/apache_kylin/kylin/tomcat/logs
    resources:
      requests:
        memory: 4Gi
        cpu: 2000m
      limits:
        memory: 4Gi
        cpu: 2000m
  volumes:
  - name: kylin-logs
    emptyDir:
      sizeLimit: 3Gi
  - name: tomcat-logs
    emptyDir:
      sizeLimit: 2Gi
  - configMap:
     name: hadoop-config
    name: hadoop-config
  - configMap:
      name: hive-config
    name: hive-config
  - configMap:
      name: hbase-config
    name: hbase-config
  - configMap:
      name: kylin-query-config
    name: kylin-query-config
  - configMap:
      name: tomcat-config
    name: tomcat-config
  - configMap:
     name: filebeat-config
    name: filebeat-config
  - configMap:
     name: kylin-more-config
    name: kylin-more-config
  restartPolicy: Never